[package]
name = "accounting-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"

rpassword = "7.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rusqlite = { version = "0.32.0", features = ["bundled"] }